name: Generate Suno Song

on:
  workflow_dispatch:

jobs:
  generate-song:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Suno song generator
        env:
          SUNO_API_KEY: ${{ secrets.SUNO_API_KEY }}
        run: |
          python generate_song.py
